package com.pvfusion.domain.operation;

public enum OperationEventType {
    LOGIN,
    LOGOUT,
    USER_APPROVED,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    PLANT_CREATED,
    PLANT_UPDATED,
    PLANT_DEACTIVATED,
    PLANT_ACCESS_GRANTED,
    PLANT_MEMBER_ROLE_CHANGED,
    PLANT_MEMBER_DEACTIVATED,
    ZONE_CREATED,
    ZONE_UPDATED,
    ZONE_DEACTIVATED,
    EQUIPMENT_CREATED,
    EQUIPMENT_UPDATED,
    EQUIPMENT_DEACTIVATED,
    IMAGE_UPLOADED,
    ANALYSIS_REQUESTED,
    RESULT_REVIEW_STATUS_CHANGED,
    RESULT_ACTION_CANDIDATE_CHANGED,
    SYSTEM_ERROR
}
